### ISSUE TITLE
The `start` parameter of the Youtube iframe does not working, it will force a jump back to the user's last viewing position.

### ISSUE THREAD

**Issue by leadra** [sound-buttons/sound-buttons#24]
https://www.youtube.com/live/Dvriyq0PTtk?si=iEl7w1M_1fWPwJb-&t=1356
Youtube 分享連結:
貼上去的瞬間是有抓到該秒數，但是預覽會馬上跳掉，變成YT的記憶最後觀看
有測試別的，第一次沒事，後面也會一直跳回記憶處

**Comment by jim60105** [comment]
筆記
https://stackoverflow.com/a/59292044
`<iframe sandbox="allow-scripts" src="..."></iframe>`

**Comment by jim60105** [comment]
問題是出在 Youtube 會記憶使用者上次的觀看記錄，並試圖從上次的觀看位置開始播放。這跟 iframe 的 [start 參數](https://developers.google.com/youtube/player_parameters#start)用途衝突，我認為是一個 (Youtube方面的) bug。

從 sound-buttons 的角度來說，解決方案是阻擋 iframe 存取 cookies，沒有用戶資訊就不會有被記錄的問題。

> 筆記 https://stackoverflow.com/a/59292044 `<iframe sandbox="allow-scripts" src="..."></iframe>`

僅使用 `sandbox="allow-scripts"` 時同時會阻擋 iframe 存取`document.caches` 導致Youtube直接罷工，需加上`sandbox="allow-scripts allow-same-origin"`。而 `allow-same-origin` 也會允許它使用 cookies，所以這個方法無法解決問題。

解決方案是[在 iframe 上使用 `credentialless`](https://developer.chrome.com/blog/iframe-credentialless)
```html
<iframe credentialless src="https://example.com">
```
這會使這個 iframe 被開啟在一個獨立的新的執行環境。它可以訪問前述需要的東西，但是是在一個新的環境，就像是使用無痕視窗(嚴格來說並不相同，但你可以簡單的如此理解)。
需要注意的是它的[支援性並不完整](https://caniuse.com/mdn-html_elements_iframe_credentialless)。在此網頁上可以測試自己的環境是否支援: [https://iframe-credentialless.glitch.me/](https://iframe-credentialless.glitch.me/)

有兩特例:

- Brave 瀏覧器實測並不支援 iframe credentialless。Brave 用戶請在 Youtube 頁面上啟用 Shields 並設定阻擋第三方 cookies。
![image](https://github.com/sound-buttons/sound-buttons/assets/16995691/9f16f2c4-55a0-4aa9-bd0e-267691d45aea)
- Safari 不支援 iframe credentialless。但是 Safari 阻擋所有的第三方 cookies，所以在我的使用情境中並沒有問題。

附註，[Chrome預計於 2024 Q3 全面停用第三方 cookies](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct)。

**Comment by jim60105** [comment]
> This is a translation for newcomers, the content is the same as the previous comment which wrote in Chinese.

The problem lies in YouTube's memory of the user's last viewing history and its attempt to start playing from the last viewed position. This conflicts with the purpose of the [start parameter](https://developers.google.com/youtube/player_parameters#start) in iframes, and I believe it is a bug on YouTube's side.

From the perspective of sound-buttons, the solution is to block iframe access to cookies so that there won't be any issues without user information.

> Note: https://stackoverflow.com/a/59292044 `<iframe sandbox="allow-scripts" src="..."></iframe>`

When using only `sandbox="allow-scripts"`, it also blocks iframe access to `document.caches`, causing YouTube to malfunction directly. It needs to be added with `sandbox="allow-scripts allow-same-origin"`. However, `allow-same-origin` also allows it to use cookies, so this method cannot solve our issue.

The solution is [to use `credentialless` on iframes](https://developer.chrome.com/blog/iframe-credentialless).

```html
<iframe credentialless src="https://example.com">
```

This will made this iframe excute in a separate new context. It can access what was mentioned above but within a new context, similar to using an incognito window (strictly speaking not exactly the same, but you can understand it simply like that).
Please note that [this feature has limited cross-browser support](https://caniuse.com/mdn-html_elements_iframe_credentialless). You can test whether your environment supports it on this webpage: [https://iframe-credentialless.glitch.me/](https://iframe-credentialless.glitch.me/)

There are two exceptions:

- Brave browser does not support iframe credentialless in actual testing. Brave users has to enable Shields on YouTube and setup to block third-party cookies.
![image](https://github.com/sound-buttons/sound-buttons/assets/16995691/9f16f2c4-55a0-4aa9-bd0e-267691d45aea)
- Safari does not support iframe credentialless. However, Safari blocks all third-party cookies, so there is no problem in our usage scenario.

Note that [Chrome plans to phase out third-party cookies by 2024 Q3](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct).

**Comment by leadra** [comment]
感謝，無法跳通知，晚回復不好意思
YT的BUG就沒辦法了，自己在YT測試好就好

**Comment by jim60105** [comment]
> 感謝，無法跳通知，晚回復不好意思 YT的BUG就沒辦法了，自己在YT測試好就好

@leadra 我有做了 workaround，它現在是可以運作的喔
除了 Brave 用戶需要如上述手動調整，除此之外都不用特別做什麼
